language: python
cache: pip
python:
  - "3.5"
before_install: cp .env.sample .env
install: pip install -r requirements.txt
script: ./manage.py $TRAVIS_STEP
env:
  - TRAVIS_STEP=isort
  - TRAVIS_STEP=tests
  - TRAVIS_STEP=flake8
